[build]
  command = "npm run build" # Replace with your app's build command
  functions = ".netlify/v1/functions" # Path to your Netlify functions
  publish = "build" # Folder containing your built frontend files

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start" # Command to start your dev server locally
  port = 3000 # Port your dev server uses
  publish = "build" # Folder with your static content
